version: '3.9'
services:

  my_django:
    build: 
      context: ./django
    image: my_django_app:1.0
    ports:
      - 8000:8000
    container_name: django_container
    command: >
      sh -c "python manage.py migrate && gunicorn todoproject.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      # - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}

  my_nginx:
    build: 
      context: ./nginx
    container_name: nginx_xontainer
    ports:
      - 80:80
    depends_on:
      - my_django

